site_name: Tower of Info

theme:
  language: es
  name: material
  logo: /assets/Tower_of_Info.png
  favicon: /assets/Tower_of_Info.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.top
    - toc.follow
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Inicio: index.md
  - Simulacrums: 
    - Simulacrums.md
    - Ling Han:
      - Ling_Han.md
    - Fei Se:
      - Fei_Se.md
  - Eventos: Eventos.md
  - Versiones: Versiones.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - neoteroi.cards
  - neoteroi.timeline
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - no-zoom
      auto_caption: false
      caption_position: bottom

extra_css:
  - css/css-v1.0.4.css