site_name: Tower of Info

theme:
  language: es
  name: material
  logo: /assets/Tower_of_Info.png
  favicon: /assets/favicon.png
  # icon:
  #   annotation: fontawesome/solid/circle-chevron-right
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.top
    # - navigation.tabs.sticky
    # - toc.follow
    - navigation.footer
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Simulacrums: Simulacrums.md
  - Eventos: Eventos.md
  - Guías: Guias.md
  # - Versiones: Versiones.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - neoteroi.cards
  - neoteroi.timeline
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra_css:
  - css/css-v1.0.4.css

extra: 
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TowerofInfo/TowerofInfo.github.io
    - icon: fontawesome/brands/discord 
      link: https://fosstodon.org/@squidfunk

copyright: Made with &#10084; by gerssh